# Generated by Django 5.2.1 on 2025-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="image_url",
            field=models.ImageField(upload_to="generated_images/"),
        ),
    ]
