# Generated by Django 5.2.1 on 2025-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
